//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string StateCity { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public Nullable<bool> Bride { get; set; }
        public Nullable<bool> Groom { get; set; }
        public string PartnerName { get; set; }
        public string PartnerIs { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> NoOfGuest { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
